// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/category/category.proto

/*
Package category is a generated protocol buffer package.

It is generated from these files:
	proto/category/category.proto

It has these top-level messages:
	Category
	CategorySlice
	UpsertCategoriesRsp
	FindCategoriesRequest
*/
package category

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Category struct {
	// @inject_tag: bson:"_id" valid:"uuid,required~ID is required"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" bson:"_id" valid:"uuid,required~ID is required"`
	// @inject_tag: bson:"name" valid:"required~name is required,length(1|256)~name must be max 256 characters"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" bson:"name" valid:"required~name is required,length(1|256)~name must be max 256 characters"`
	// @inject_tag: valid:"required~Slug is required"
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty" valid:"required~Slug is required"`
	// @inject_tag: bson:"display_order"
	DisplayOrder uint64 `protobuf:"varint,4,opt,name=display_order,json=displayOrder" json:"display_order,omitempty" bson:"display_order"`
	// @inject_tag: valid:"required~Description is required"
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty" valid:"required~Description is required"`
	Hidden      bool   `protobuf:"varint,6,opt,name=hidden" json:"hidden,omitempty"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" bson:"updated_at"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Category) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Category) GetDisplayOrder() uint64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Category) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *Category) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Category) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CategorySlice struct {
	Categories []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
}

func (m *CategorySlice) Reset()                    { *m = CategorySlice{} }
func (m *CategorySlice) String() string            { return proto.CompactTextString(m) }
func (*CategorySlice) ProtoMessage()               {}
func (*CategorySlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CategorySlice) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type UpsertCategoriesRsp struct {
	Updated int64 `protobuf:"varint,1,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpsertCategoriesRsp) Reset()                    { *m = UpsertCategoriesRsp{} }
func (m *UpsertCategoriesRsp) String() string            { return proto.CompactTextString(m) }
func (*UpsertCategoriesRsp) ProtoMessage()               {}
func (*UpsertCategoriesRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpsertCategoriesRsp) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type FindCategoriesRequest struct {
	Ids         []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	Query       string   `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	Hidden      bool     `protobuf:"varint,3,opt,name=hidden" json:"hidden,omitempty"`
	Sort        []string `protobuf:"bytes,4,rep,name=sort" json:"sort,omitempty"`
	PerPage     int64    `protobuf:"varint,5,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
	CurrentPage int64    `protobuf:"varint,6,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
}

func (m *FindCategoriesRequest) Reset()                    { *m = FindCategoriesRequest{} }
func (m *FindCategoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*FindCategoriesRequest) ProtoMessage()               {}
func (*FindCategoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FindCategoriesRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FindCategoriesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *FindCategoriesRequest) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *FindCategoriesRequest) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *FindCategoriesRequest) GetPerPage() int64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *FindCategoriesRequest) GetCurrentPage() int64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func init() {
	proto.RegisterType((*Category)(nil), "go.micro.srv.courses.Category")
	proto.RegisterType((*CategorySlice)(nil), "go.micro.srv.courses.CategorySlice")
	proto.RegisterType((*UpsertCategoriesRsp)(nil), "go.micro.srv.courses.UpsertCategoriesRsp")
	proto.RegisterType((*FindCategoriesRequest)(nil), "go.micro.srv.courses.FindCategoriesRequest")
}

func init() { proto.RegisterFile("proto/category/category.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x95, 0xa6, 0xeb, 0xda, 0xd3, 0x6d, 0x9a, 0x0e, 0x03, 0x99, 0x4a, 0x40, 0xe8, 0x6e,
	0x82, 0x90, 0x52, 0xa9, 0x5c, 0x71, 0x83, 0x34, 0x36, 0x21, 0xed, 0x6a, 0xc8, 0xc0, 0x0d, 0x37,
	0x55, 0x1a, 0x1f, 0x82, 0xa5, 0x36, 0xf6, 0x6c, 0x07, 0xa9, 0x4f, 0xc2, 0x33, 0xf0, 0x3e, 0x3c,
	0x10, 0x8a, 0xe3, 0x8c, 0x0e, 0x45, 0xc0, 0xdd, 0xf1, 0xef, 0xff, 0x77, 0xcf, 0xf9, 0x4e, 0x03,
	0x4f, 0xb4, 0x51, 0x4e, 0x2d, 0x8a, 0xdc, 0x51, 0xa9, 0xcc, 0xee, 0xae, 0xc8, 0xbc, 0x8e, 0x67,
	0xa5, 0xca, 0xb6, 0xb2, 0x30, 0x2a, 0xb3, 0xe6, 0x5b, 0x56, 0xa8, 0xda, 0x58, 0xb2, 0xb3, 0x67,
	0xa5, 0x52, 0xe5, 0x86, 0x16, 0xde, 0xb3, 0xae, 0xbf, 0x2c, 0x9c, 0xdc, 0x92, 0x75, 0xf9, 0x56,
	0xb7, 0xb1, 0xf9, 0xf7, 0x01, 0x8c, 0x2f, 0xc3, 0x4b, 0x78, 0x02, 0x83, 0xeb, 0x2b, 0x16, 0x25,
	0x51, 0x3a, 0xe1, 0x83, 0xeb, 0x2b, 0x44, 0x18, 0x56, 0xf9, 0x96, 0xd8, 0xc0, 0x2b, 0xbe, 0x6e,
	0x34, 0xbb, 0xa9, 0x4b, 0x16, 0xb7, 0x5a, 0x53, 0xe3, 0x39, 0x1c, 0x0b, 0x69, 0xf5, 0x26, 0xdf,
	0xad, 0x94, 0x11, 0x64, 0xd8, 0x30, 0x89, 0xd2, 0x21, 0x3f, 0x0a, 0xe2, 0x4d, 0xa3, 0x61, 0x02,
	0x53, 0x41, 0xb6, 0x30, 0x52, 0x3b, 0xa9, 0x2a, 0x76, 0xe0, 0xf3, 0xfb, 0x12, 0x3e, 0x82, 0xd1,
	0x57, 0x29, 0x04, 0x55, 0x6c, 0x94, 0x44, 0xe9, 0x98, 0x87, 0x13, 0xbe, 0x06, 0x28, 0x0c, 0xe5,
	0x8e, 0xc4, 0x2a, 0x77, 0x6c, 0x92, 0x44, 0xe9, 0x74, 0x39, 0xcb, 0xda, 0xc9, 0xb2, 0x6e, 0xb2,
	0xec, 0x63, 0x37, 0x19, 0x9f, 0x04, 0xf7, 0x85, 0x6b, 0xa2, 0xb5, 0x16, 0x5d, 0x14, 0xfe, 0x1d,
	0x0d, 0xee, 0x0b, 0x37, 0xbf, 0x81, 0xe3, 0x0e, 0xcc, 0x87, 0x8d, 0x2c, 0x08, 0xdf, 0x00, 0x04,
	0xe6, 0x92, 0x2c, 0x8b, 0x92, 0x38, 0x9d, 0x2e, 0x9f, 0x66, 0x7d, 0xd8, 0xb3, 0x2e, 0xc8, 0xf7,
	0x12, 0xf3, 0x05, 0x3c, 0xf8, 0xa4, 0x2d, 0x19, 0x77, 0x79, 0xa7, 0x71, 0xab, 0x91, 0xc1, 0x61,
	0xf8, 0x51, 0x4f, 0x3e, 0xe6, 0xdd, 0x71, 0xfe, 0x23, 0x82, 0x87, 0xef, 0x64, 0x25, 0xf6, 0xfc,
	0x74, 0x5b, 0x93, 0x75, 0x78, 0x0a, 0xb1, 0x14, 0x6d, 0x0f, 0x13, 0xde, 0x94, 0x78, 0x06, 0x07,
	0xb7, 0x35, 0x99, 0x5d, 0xd8, 0x55, 0x7b, 0xd8, 0x23, 0x1a, 0xdf, 0x23, 0xda, 0x2c, 0x51, 0x19,
	0xc7, 0x86, 0xfe, 0x01, 0x5f, 0xe3, 0x63, 0x18, 0x6b, 0x32, 0x2b, 0x9d, 0x97, 0xe4, 0x97, 0x13,
	0xf3, 0x43, 0x4d, 0xe6, 0x7d, 0x5e, 0x12, 0x3e, 0x87, 0xa3, 0xa2, 0x36, 0x86, 0x2a, 0xd7, 0x5e,
	0x8f, 0xfc, 0xf5, 0x34, 0x68, 0x8d, 0x65, 0xf9, 0x33, 0x02, 0xf8, 0xdd, 0x27, 0xae, 0xe1, 0xf4,
	0xcf, 0x59, 0xf1, 0xfc, 0xef, 0xac, 0x3c, 0xe4, 0xd9, 0x8b, 0x7e, 0x53, 0x1f, 0xb8, 0x35, 0x9c,
	0xdc, 0xa7, 0x83, 0x2f, 0xfb, 0xc3, 0xbd, 0x0c, 0x67, 0xff, 0xd3, 0xce, 0x5b, 0xf8, 0x3c, 0xee,
	0xbe, 0xb3, 0xf5, 0xc8, 0xff, 0x5f, 0x5e, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x94, 0x6c,
	0x7b, 0x89, 0x03, 0x00, 0x00,
}
