// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/category/category.proto

/*
Package category is a generated protocol buffer package.

It is generated from these files:
	proto/category/category.proto

It has these top-level messages:
	Category
	CategorySlice
	UpsertCategoriesRsp
	FindCategoriesRequest
*/
package category

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Categories service

type CategoriesClient interface {
	UpsertCategories(ctx context.Context, in *CategorySlice, opts ...client.CallOption) (*UpsertCategoriesRsp, error)
	FindCategories(ctx context.Context, in *FindCategoriesRequest, opts ...client.CallOption) (*CategorySlice, error)
}

type categoriesClient struct {
	c           client.Client
	serviceName string
}

func NewCategoriesClient(serviceName string, c client.Client) CategoriesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.courses"
	}
	return &categoriesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *categoriesClient) UpsertCategories(ctx context.Context, in *CategorySlice, opts ...client.CallOption) (*UpsertCategoriesRsp, error) {
	req := c.c.NewRequest(c.serviceName, "Categories.UpsertCategories", in)
	out := new(UpsertCategoriesRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoriesClient) FindCategories(ctx context.Context, in *FindCategoriesRequest, opts ...client.CallOption) (*CategorySlice, error) {
	req := c.c.NewRequest(c.serviceName, "Categories.FindCategories", in)
	out := new(CategorySlice)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Categories service

type CategoriesHandler interface {
	UpsertCategories(context.Context, *CategorySlice, *UpsertCategoriesRsp) error
	FindCategories(context.Context, *FindCategoriesRequest, *CategorySlice) error
}

func RegisterCategoriesHandler(s server.Server, hdlr CategoriesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Categories{hdlr}, opts...))
}

type Categories struct {
	CategoriesHandler
}

func (h *Categories) UpsertCategories(ctx context.Context, in *CategorySlice, out *UpsertCategoriesRsp) error {
	return h.CategoriesHandler.UpsertCategories(ctx, in, out)
}

func (h *Categories) FindCategories(ctx context.Context, in *FindCategoriesRequest, out *CategorySlice) error {
	return h.CategoriesHandler.FindCategories(ctx, in, out)
}
