// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/course/course.proto

/*
Package course is a generated protocol buffer package.

It is generated from these files:
	proto/course/course.proto

It has these top-level messages:
	UpsertCourseReq
	UpsertCourseRsp
	InsertCoursesRsp
	DeleteCoursesRsp
	IDs
	UpdateCoursesRsp
	FindCoursesRsp
	Courses
	FindCoursesReq
	Course
*/
package course

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CourseService service

type CourseServiceClient interface {
	UpsertCourse(ctx context.Context, in *UpsertCourseReq, opts ...client.CallOption) (*UpsertCourseRsp, error)
	InsertCourses(ctx context.Context, in *Courses, opts ...client.CallOption) (*InsertCoursesRsp, error)
	UpdateCourses(ctx context.Context, in *Courses, opts ...client.CallOption) (*UpdateCoursesRsp, error)
	FindCourses(ctx context.Context, in *FindCoursesReq, opts ...client.CallOption) (*FindCoursesRsp, error)
	DeleteCoursesByIDs(ctx context.Context, in *IDs, opts ...client.CallOption) (*DeleteCoursesRsp, error)
}

type courseServiceClient struct {
	c           client.Client
	serviceName string
}

func NewCourseServiceClient(serviceName string, c client.Client) CourseServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.courses"
	}
	return &courseServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *courseServiceClient) UpsertCourse(ctx context.Context, in *UpsertCourseReq, opts ...client.CallOption) (*UpsertCourseRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CourseService.UpsertCourse", in)
	out := new(UpsertCourseRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) InsertCourses(ctx context.Context, in *Courses, opts ...client.CallOption) (*InsertCoursesRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CourseService.InsertCourses", in)
	out := new(InsertCoursesRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) UpdateCourses(ctx context.Context, in *Courses, opts ...client.CallOption) (*UpdateCoursesRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CourseService.UpdateCourses", in)
	out := new(UpdateCoursesRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) FindCourses(ctx context.Context, in *FindCoursesReq, opts ...client.CallOption) (*FindCoursesRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CourseService.FindCourses", in)
	out := new(FindCoursesRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) DeleteCoursesByIDs(ctx context.Context, in *IDs, opts ...client.CallOption) (*DeleteCoursesRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CourseService.DeleteCoursesByIDs", in)
	out := new(DeleteCoursesRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CourseService service

type CourseServiceHandler interface {
	UpsertCourse(context.Context, *UpsertCourseReq, *UpsertCourseRsp) error
	InsertCourses(context.Context, *Courses, *InsertCoursesRsp) error
	UpdateCourses(context.Context, *Courses, *UpdateCoursesRsp) error
	FindCourses(context.Context, *FindCoursesReq, *FindCoursesRsp) error
	DeleteCoursesByIDs(context.Context, *IDs, *DeleteCoursesRsp) error
}

func RegisterCourseServiceHandler(s server.Server, hdlr CourseServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&CourseService{hdlr}, opts...))
}

type CourseService struct {
	CourseServiceHandler
}

func (h *CourseService) UpsertCourse(ctx context.Context, in *UpsertCourseReq, out *UpsertCourseRsp) error {
	return h.CourseServiceHandler.UpsertCourse(ctx, in, out)
}

func (h *CourseService) InsertCourses(ctx context.Context, in *Courses, out *InsertCoursesRsp) error {
	return h.CourseServiceHandler.InsertCourses(ctx, in, out)
}

func (h *CourseService) UpdateCourses(ctx context.Context, in *Courses, out *UpdateCoursesRsp) error {
	return h.CourseServiceHandler.UpdateCourses(ctx, in, out)
}

func (h *CourseService) FindCourses(ctx context.Context, in *FindCoursesReq, out *FindCoursesRsp) error {
	return h.CourseServiceHandler.FindCourses(ctx, in, out)
}

func (h *CourseService) DeleteCoursesByIDs(ctx context.Context, in *IDs, out *DeleteCoursesRsp) error {
	return h.CourseServiceHandler.DeleteCoursesByIDs(ctx, in, out)
}
