// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course/course.proto

/*
Package course is a generated protocol buffer package.

It is generated from these files:
	proto/course/course.proto

It has these top-level messages:
	UpdateCoursesRsp
	CourseSlice
	FindCoursesRequest
	Course
*/
package course

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/jianhan/pkg/proto/mysql"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateCoursesRsp struct {
	Updated int64 `protobuf:"varint,1,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpdateCoursesRsp) Reset()                    { *m = UpdateCoursesRsp{} }
func (m *UpdateCoursesRsp) String() string            { return proto.CompactTextString(m) }
func (*UpdateCoursesRsp) ProtoMessage()               {}
func (*UpdateCoursesRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateCoursesRsp) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type CourseSlice struct {
	Courses []*Course `protobuf:"bytes,1,rep,name=courses" json:"courses,omitempty"`
}

func (m *CourseSlice) Reset()                    { *m = CourseSlice{} }
func (m *CourseSlice) String() string            { return proto.CompactTextString(m) }
func (*CourseSlice) ProtoMessage()               {}
func (*CourseSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CourseSlice) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type FindCoursesRequest struct {
	Ids         []string                   `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	Query       string                     `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	Start       *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=start" json:"start,omitempty"`
	End         *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=end" json:"end,omitempty"`
	Inclusive   bool                       `protobuf:"varint,5,opt,name=inclusive" json:"inclusive,omitempty"`
	Hidden      bool                       `protobuf:"varint,6,opt,name=hidden" json:"hidden,omitempty"`
	OrderBy     string                     `protobuf:"bytes,7,opt,name=order_by,json=orderBy" json:"order_by,omitempty"`
	OrderDir    string                     `protobuf:"bytes,9,opt,name=order_dir,json=orderDir" json:"order_dir,omitempty"`
	PerPage     int64                      `protobuf:"varint,10,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
	CurrentPage int64                      `protobuf:"varint,11,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
}

func (m *FindCoursesRequest) Reset()                    { *m = FindCoursesRequest{} }
func (m *FindCoursesRequest) String() string            { return proto.CompactTextString(m) }
func (*FindCoursesRequest) ProtoMessage()               {}
func (*FindCoursesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FindCoursesRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FindCoursesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *FindCoursesRequest) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *FindCoursesRequest) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *FindCoursesRequest) GetInclusive() bool {
	if m != nil {
		return m.Inclusive
	}
	return false
}

func (m *FindCoursesRequest) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *FindCoursesRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *FindCoursesRequest) GetOrderDir() string {
	if m != nil {
		return m.OrderDir
	}
	return ""
}

func (m *FindCoursesRequest) GetPerPage() int64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *FindCoursesRequest) GetCurrentPage() int64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

// Course defines data structure of Course.
type Course struct {
	// @inject_tag: bson:"_id" valid:"uuid,required~ID is required"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" bson:"_id" valid:"uuid,required~ID is required"`
	// @inject_tag: bson:"name" valid:"required~name is required,length(1|256)~name must be max 256 characters"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" bson:"name" valid:"required~name is required,length(1|256)~name must be max 256 characters"`
	// @inject_tag: valid:"required~Slug is required"
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty" valid:"required~Slug is required"`
	// @inject_tag: bson:"display_order"
	DisplayOrder uint64 `protobuf:"varint,4,opt,name=display_order,json=displayOrder" json:"display_order,omitempty" bson:"display_order"`
	// @inject_tag: valid:"required~Description is required"
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty" valid:"required~Description is required"`
	Hidden      bool   `protobuf:"varint,6,opt,name=hidden" json:"hidden,omitempty"`
	// @inject_tag: valid:"required~Start date time is required"
	Start *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=start" json:"start,omitempty" valid:"required~Start date time is required"`
	// @inject_tag: valid:"required~End date time is required"
	End *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=end" json:"end,omitempty" valid:"required~End date time is required"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" bson:"updated_at"`
	// @inject_tag: bson:"category_ids"
	CategoryIds []string `protobuf:"bytes,11,rep,name=category_ids,json=categoryIds" json:"category_ids,omitempty" bson:"category_ids"`
}

func (m *Course) Reset()                    { *m = Course{} }
func (m *Course) String() string            { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()               {}
func (*Course) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Course) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Course) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Course) GetDisplayOrder() uint64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *Course) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Course) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Course) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Course) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Course) GetCategoryIds() []string {
	if m != nil {
		return m.CategoryIds
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateCoursesRsp)(nil), "go.micro.srv.courses.UpdateCoursesRsp")
	proto.RegisterType((*CourseSlice)(nil), "go.micro.srv.courses.CourseSlice")
	proto.RegisterType((*FindCoursesRequest)(nil), "go.micro.srv.courses.FindCoursesRequest")
	proto.RegisterType((*Course)(nil), "go.micro.srv.courses.Course")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Courses service

type CoursesClient interface {
	InsertCourses(ctx context.Context, in *CourseSlice, opts ...client.CallOption) (*google_protobuf1.Empty, error)
	UpdateCourses(ctx context.Context, in *CourseSlice, opts ...client.CallOption) (*UpdateCoursesRsp, error)
	FindCourses(ctx context.Context, in *FindCoursesRequest, opts ...client.CallOption) (*CourseSlice, error)
}

type coursesClient struct {
	c           client.Client
	serviceName string
}

func NewCoursesClient(serviceName string, c client.Client) CoursesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.courses"
	}
	return &coursesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *coursesClient) InsertCourses(ctx context.Context, in *CourseSlice, opts ...client.CallOption) (*google_protobuf1.Empty, error) {
	req := c.c.NewRequest(c.serviceName, "Courses.InsertCourses", in)
	out := new(google_protobuf1.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) UpdateCourses(ctx context.Context, in *CourseSlice, opts ...client.CallOption) (*UpdateCoursesRsp, error) {
	req := c.c.NewRequest(c.serviceName, "Courses.UpdateCourses", in)
	out := new(UpdateCoursesRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) FindCourses(ctx context.Context, in *FindCoursesRequest, opts ...client.CallOption) (*CourseSlice, error) {
	req := c.c.NewRequest(c.serviceName, "Courses.FindCourses", in)
	out := new(CourseSlice)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Courses service

type CoursesHandler interface {
	InsertCourses(context.Context, *CourseSlice, *google_protobuf1.Empty) error
	UpdateCourses(context.Context, *CourseSlice, *UpdateCoursesRsp) error
	FindCourses(context.Context, *FindCoursesRequest, *CourseSlice) error
}

func RegisterCoursesHandler(s server.Server, hdlr CoursesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Courses{hdlr}, opts...))
}

type Courses struct {
	CoursesHandler
}

func (h *Courses) InsertCourses(ctx context.Context, in *CourseSlice, out *google_protobuf1.Empty) error {
	return h.CoursesHandler.InsertCourses(ctx, in, out)
}

func (h *Courses) UpdateCourses(ctx context.Context, in *CourseSlice, out *UpdateCoursesRsp) error {
	return h.CoursesHandler.UpdateCourses(ctx, in, out)
}

func (h *Courses) FindCourses(ctx context.Context, in *FindCoursesRequest, out *CourseSlice) error {
	return h.CoursesHandler.FindCourses(ctx, in, out)
}

func init() { proto.RegisterFile("proto/course/course.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0xe3, 0x36, 0x8e, 0xc7, 0xed, 0x4f, 0xd5, 0xaa, 0xaa, 0xdc, 0xb4, 0xd2, 0xcf, 0x0d,
	0x12, 0xf2, 0xa1, 0xb2, 0x51, 0x91, 0x90, 0x38, 0xb6, 0xa4, 0x48, 0xe1, 0x02, 0x32, 0x70, 0xc9,
	0x25, 0x72, 0xbc, 0x83, 0xb3, 0xe0, 0x7f, 0xd9, 0x5d, 0x57, 0xf2, 0x87, 0xe0, 0xce, 0x47, 0xe2,
	0x63, 0x21, 0xef, 0xda, 0x50, 0x48, 0x68, 0xca, 0x25, 0xd9, 0x7d, 0xf3, 0xde, 0x7a, 0xe6, 0xcd,
	0x0c, 0x9c, 0x56, 0xbc, 0x94, 0x65, 0x98, 0x94, 0x35, 0x17, 0xd8, 0xfd, 0x05, 0x0a, 0x23, 0xc7,
	0x69, 0x19, 0xe4, 0x2c, 0xe1, 0x65, 0x20, 0xf8, 0x5d, 0xa0, 0x43, 0x62, 0xfc, 0x7f, 0x5a, 0x96,
	0x69, 0x86, 0xa1, 0xe2, 0x2c, 0xeb, 0x4f, 0xa1, 0x64, 0x39, 0x0a, 0x19, 0xe7, 0x95, 0x96, 0x8d,
	0x83, 0x94, 0xc9, 0x55, 0xbd, 0x0c, 0x92, 0x32, 0x0f, 0x3f, 0xb3, 0xb8, 0x58, 0xc5, 0x45, 0x58,
	0x7d, 0x49, 0xb5, 0x20, 0xcc, 0x1b, 0xb1, 0xce, 0xf4, 0x6f, 0xc7, 0x3f, 0xfb, 0xf3, 0x41, 0xcc,
	0x2b, 0xd9, 0xe8, 0xe0, 0xe4, 0x12, 0x8e, 0x3e, 0x56, 0x34, 0x96, 0xf8, 0x4a, 0x7f, 0x3e, 0x12,
	0x15, 0x71, 0xc1, 0xaa, 0x15, 0x46, 0x5d, 0xc3, 0x33, 0x7c, 0x33, 0xea, 0xaf, 0x93, 0x5b, 0x70,
	0x34, 0xef, 0x7d, 0xc6, 0x12, 0x24, 0x2f, 0xc0, 0xea, 0xb2, 0x76, 0x0d, 0xcf, 0xf4, 0x9d, 0xab,
	0xf3, 0x60, 0x5b, 0x49, 0x81, 0xd6, 0x44, 0x3d, 0x79, 0xf2, 0x7d, 0x00, 0xe4, 0x35, 0x2b, 0x68,
	0xff, 0x4d, 0x5c, 0xd7, 0x28, 0x24, 0x39, 0x02, 0x93, 0x51, 0xfd, 0x94, 0x1d, 0xb5, 0x47, 0x72,
	0x0c, 0xfb, 0xeb, 0x1a, 0x79, 0xe3, 0x0e, 0x3c, 0xc3, 0xb7, 0x23, 0x7d, 0x21, 0xcf, 0x60, 0x5f,
	0xc8, 0x98, 0x4b, 0xd7, 0xf4, 0x0c, 0xdf, 0xb9, 0x1a, 0x07, 0xba, 0xc0, 0xa0, 0x2f, 0x30, 0xf8,
	0xd0, 0x3b, 0x16, 0x69, 0x22, 0xb9, 0x04, 0x13, 0x0b, 0xea, 0xee, 0xed, 0xe4, 0xb7, 0x34, 0x72,
	0x0e, 0x36, 0x2b, 0x92, 0xac, 0x16, 0xec, 0x0e, 0xdd, 0x7d, 0xcf, 0xf0, 0x47, 0xd1, 0x2f, 0x80,
	0x9c, 0xc0, 0x70, 0xc5, 0x28, 0xc5, 0xc2, 0x1d, 0xaa, 0x50, 0x77, 0x23, 0xa7, 0x30, 0x2a, 0x39,
	0x45, 0xbe, 0x58, 0x36, 0xae, 0xa5, 0xd2, 0xb5, 0xd4, 0xfd, 0xa6, 0x21, 0x67, 0x60, 0xeb, 0x10,
	0x65, 0xdc, 0xb5, 0x55, 0x4c, 0x73, 0xa7, 0x8c, 0xb7, 0xba, 0x0a, 0xf9, 0xa2, 0x8a, 0x53, 0x74,
	0x41, 0xdb, 0x5d, 0x21, 0x7f, 0x17, 0xa7, 0x48, 0x2e, 0xe0, 0x20, 0xa9, 0x39, 0xc7, 0x42, 0xea,
	0xb0, 0xa3, 0xc2, 0x4e, 0x87, 0xb5, 0x94, 0xc9, 0x37, 0x13, 0x86, 0xda, 0x46, 0xf2, 0x1f, 0x0c,
	0x66, 0x53, 0xd5, 0x31, 0x3b, 0x1a, 0xcc, 0xa6, 0x84, 0xc0, 0x5e, 0x11, 0xe7, 0xd8, 0x79, 0xa7,
	0xce, 0x2d, 0x26, 0xb2, 0x3a, 0x55, 0xce, 0xd9, 0x91, 0x3a, 0x93, 0x27, 0x70, 0x48, 0x99, 0xa8,
	0xb2, 0xb8, 0x59, 0xa8, 0xa4, 0x94, 0x4d, 0x7b, 0xd1, 0x41, 0x07, 0xbe, 0x6d, 0x31, 0xe2, 0x81,
	0x43, 0x51, 0x24, 0x9c, 0x55, 0x92, 0x95, 0x85, 0x72, 0xc5, 0x8e, 0xee, 0x43, 0x7f, 0xf5, 0xe5,
	0x67, 0xb7, 0xac, 0x7f, 0xec, 0xd6, 0xe8, 0x71, 0xdd, 0x7a, 0x09, 0x90, 0x70, 0x6c, 0xc7, 0x73,
	0x11, 0x4b, 0xe5, 0xee, 0xc3, 0x22, 0xbb, 0x63, 0x5f, 0xcb, 0x56, 0xda, 0x4d, 0x76, 0x2b, 0x85,
	0xdd, 0xd2, 0x8e, 0x7d, 0x2d, 0x55, 0x6b, 0x62, 0x89, 0x69, 0xc9, 0x9b, 0x45, 0x3b, 0xb4, 0x8e,
	0x1a, 0x5a, 0xa7, 0xc7, 0x66, 0x54, 0x5c, 0x7d, 0x1d, 0x80, 0xd5, 0x4d, 0x38, 0x79, 0x03, 0x87,
	0xb3, 0x42, 0x20, 0x97, 0x3d, 0x70, 0xf1, 0xd0, 0xa6, 0xa8, 0xed, 0x1a, 0x9f, 0x6c, 0x64, 0x72,
	0xdb, 0x2e, 0x2e, 0x99, 0xc3, 0xe1, 0x6f, 0x2b, 0xfb, 0x98, 0xb7, 0x9e, 0x6e, 0xa7, 0x6c, 0xac,
	0xfe, 0x1c, 0x9c, 0x7b, 0x8b, 0x49, 0xfc, 0xed, 0xb2, 0xcd, 0xdd, 0x1d, 0xef, 0xce, 0xe1, 0x66,
	0x34, 0x1f, 0x6a, 0x78, 0x39, 0x54, 0x15, 0x3d, 0xff, 0x11, 0x00, 0x00, 0xff, 0xff, 0x68, 0x8c,
	0xba, 0x09, 0x1c, 0x05, 0x00, 0x00,
}
