// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course/course.proto

/*
Package course is a generated protocol buffer package.

It is generated from these files:
	proto/course/course.proto

It has these top-level messages:
	UpsertCourseReq
	UpsertCourseRsp
	InsertCoursesRsp
	DeleteCoursesRsp
	IDs
	UpdateCoursesRsp
	FindCoursesRsp
	Courses
	FindCoursesReq
	Course
*/
package course

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpsertCourseReq struct {
	Course *Course `protobuf:"bytes,1,opt,name=course" json:"course,omitempty"`
	IsNew  bool    `protobuf:"varint,2,opt,name=is_new,json=isNew" json:"is_new,omitempty"`
}

func (m *UpsertCourseReq) Reset()                    { *m = UpsertCourseReq{} }
func (m *UpsertCourseReq) String() string            { return proto.CompactTextString(m) }
func (*UpsertCourseReq) ProtoMessage()               {}
func (*UpsertCourseReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpsertCourseReq) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *UpsertCourseReq) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

type UpsertCourseRsp struct {
	Course   *Course `protobuf:"bytes,1,opt,name=course" json:"course,omitempty"`
	Inserted int64   `protobuf:"varint,2,opt,name=inserted" json:"inserted,omitempty"`
	Updated  int64   `protobuf:"varint,3,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpsertCourseRsp) Reset()                    { *m = UpsertCourseRsp{} }
func (m *UpsertCourseRsp) String() string            { return proto.CompactTextString(m) }
func (*UpsertCourseRsp) ProtoMessage()               {}
func (*UpsertCourseRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpsertCourseRsp) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *UpsertCourseRsp) GetInserted() int64 {
	if m != nil {
		return m.Inserted
	}
	return 0
}

func (m *UpsertCourseRsp) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type InsertCoursesRsp struct {
	Inserted int64 `protobuf:"varint,1,opt,name=inserted" json:"inserted,omitempty"`
}

func (m *InsertCoursesRsp) Reset()                    { *m = InsertCoursesRsp{} }
func (m *InsertCoursesRsp) String() string            { return proto.CompactTextString(m) }
func (*InsertCoursesRsp) ProtoMessage()               {}
func (*InsertCoursesRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InsertCoursesRsp) GetInserted() int64 {
	if m != nil {
		return m.Inserted
	}
	return 0
}

type DeleteCoursesRsp struct {
	Deleted int64 `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteCoursesRsp) Reset()                    { *m = DeleteCoursesRsp{} }
func (m *DeleteCoursesRsp) String() string            { return proto.CompactTextString(m) }
func (*DeleteCoursesRsp) ProtoMessage()               {}
func (*DeleteCoursesRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteCoursesRsp) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type IDs struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *IDs) Reset()                    { *m = IDs{} }
func (m *IDs) String() string            { return proto.CompactTextString(m) }
func (*IDs) ProtoMessage()               {}
func (*IDs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IDs) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type UpdateCoursesRsp struct {
	Updated int64 `protobuf:"varint,1,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpdateCoursesRsp) Reset()                    { *m = UpdateCoursesRsp{} }
func (m *UpdateCoursesRsp) String() string            { return proto.CompactTextString(m) }
func (*UpdateCoursesRsp) ProtoMessage()               {}
func (*UpdateCoursesRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateCoursesRsp) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type FindCoursesRsp struct {
	Courses []*Course `protobuf:"bytes,1,rep,name=courses" json:"courses,omitempty"`
}

func (m *FindCoursesRsp) Reset()                    { *m = FindCoursesRsp{} }
func (m *FindCoursesRsp) String() string            { return proto.CompactTextString(m) }
func (*FindCoursesRsp) ProtoMessage()               {}
func (*FindCoursesRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FindCoursesRsp) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type Courses struct {
	Courses []*Course `protobuf:"bytes,1,rep,name=courses" json:"courses,omitempty"`
}

func (m *Courses) Reset()                    { *m = Courses{} }
func (m *Courses) String() string            { return proto.CompactTextString(m) }
func (*Courses) ProtoMessage()               {}
func (*Courses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Courses) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type FindCoursesReq struct {
	Ids         []string                   `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	Query       string                     `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	Start       *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=start" json:"start,omitempty"`
	End         *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=end" json:"end,omitempty"`
	Inclusive   bool                       `protobuf:"varint,5,opt,name=inclusive" json:"inclusive,omitempty"`
	Hidden      bool                       `protobuf:"varint,6,opt,name=hidden" json:"hidden,omitempty"`
	Sort        []string                   `protobuf:"bytes,7,rep,name=sort" json:"sort,omitempty"`
	PerPage     int64                      `protobuf:"varint,8,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
	CurrentPage int64                      `protobuf:"varint,9,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
}

func (m *FindCoursesReq) Reset()                    { *m = FindCoursesReq{} }
func (m *FindCoursesReq) String() string            { return proto.CompactTextString(m) }
func (*FindCoursesReq) ProtoMessage()               {}
func (*FindCoursesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FindCoursesReq) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FindCoursesReq) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *FindCoursesReq) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *FindCoursesReq) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *FindCoursesReq) GetInclusive() bool {
	if m != nil {
		return m.Inclusive
	}
	return false
}

func (m *FindCoursesReq) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *FindCoursesReq) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *FindCoursesReq) GetPerPage() int64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *FindCoursesReq) GetCurrentPage() int64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

// Course defines data structure of Course.
type Course struct {
	// @inject_tag: bson:"_id" valid:"uuid,required~ID is required"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" bson:"_id" valid:"uuid,required~ID is required"`
	// @inject_tag: bson:"name" valid:"required~name is required,length(1|256)~name must be max 256 characters"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" bson:"name" valid:"required~name is required,length(1|256)~name must be max 256 characters"`
	// @inject_tag: valid:"required~Slug is required"
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty" valid:"required~Slug is required"`
	// @inject_tag: bson:"display_order"
	DisplayOrder uint64 `protobuf:"varint,4,opt,name=display_order,json=displayOrder" json:"display_order,omitempty" bson:"display_order"`
	// @inject_tag: valid:"required~Description is required"
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty" valid:"required~Description is required"`
	Hidden      bool   `protobuf:"varint,6,opt,name=hidden" json:"hidden,omitempty"`
	// @inject_tag: valid:"required~Start date time is required"
	Start *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=start" json:"start,omitempty" valid:"required~Start date time is required"`
	// @inject_tag: valid:"required~End date time is required"
	End *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=end" json:"end,omitempty" valid:"required~End date time is required"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" bson:"updated_at"`
	// @inject_tag: bson:"category_ids"
	CategoryIds []string `protobuf:"bytes,11,rep,name=category_ids,json=categoryIds" json:"category_ids,omitempty" bson:"category_ids"`
}

func (m *Course) Reset()                    { *m = Course{} }
func (m *Course) String() string            { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()               {}
func (*Course) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Course) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Course) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Course) GetDisplayOrder() uint64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *Course) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Course) GetEnd() *google_protobuf.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Course) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Course) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Course) GetCategoryIds() []string {
	if m != nil {
		return m.CategoryIds
	}
	return nil
}

func init() {
	proto.RegisterType((*UpsertCourseReq)(nil), "go.micro.srv.courses.UpsertCourseReq")
	proto.RegisterType((*UpsertCourseRsp)(nil), "go.micro.srv.courses.UpsertCourseRsp")
	proto.RegisterType((*InsertCoursesRsp)(nil), "go.micro.srv.courses.InsertCoursesRsp")
	proto.RegisterType((*DeleteCoursesRsp)(nil), "go.micro.srv.courses.DeleteCoursesRsp")
	proto.RegisterType((*IDs)(nil), "go.micro.srv.courses.IDs")
	proto.RegisterType((*UpdateCoursesRsp)(nil), "go.micro.srv.courses.UpdateCoursesRsp")
	proto.RegisterType((*FindCoursesRsp)(nil), "go.micro.srv.courses.FindCoursesRsp")
	proto.RegisterType((*Courses)(nil), "go.micro.srv.courses.Courses")
	proto.RegisterType((*FindCoursesReq)(nil), "go.micro.srv.courses.FindCoursesReq")
	proto.RegisterType((*Course)(nil), "go.micro.srv.courses.Course")
}

func init() { proto.RegisterFile("proto/course/course.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x56, 0xe2, 0xe6, 0xc3, 0xe3, 0xa6, 0x6f, 0xb5, 0xea, 0x0b, 0x6e, 0x54, 0x44, 0x30, 0x1f,
	0xea, 0xa1, 0x72, 0x51, 0x41, 0x48, 0x1c, 0x5b, 0x22, 0x44, 0x2e, 0x80, 0x0c, 0x2d, 0x02, 0x21,
	0x22, 0xd7, 0x1e, 0xcc, 0x4a, 0x89, 0xed, 0xee, 0xae, 0x5b, 0xe5, 0xc0, 0xff, 0xe0, 0xc8, 0x5f,
	0xe2, 0x1f, 0xa1, 0x1d, 0xaf, 0xdb, 0xb8, 0x4d, 0x3f, 0xe8, 0x29, 0x9e, 0x99, 0x67, 0x9e, 0x9d,
	0x9d, 0x67, 0x76, 0x02, 0xeb, 0xb9, 0xc8, 0x54, 0xb6, 0x1d, 0x65, 0x85, 0x90, 0x68, 0x7e, 0x7c,
	0xf2, 0xb1, 0xb5, 0x24, 0xf3, 0xa7, 0x3c, 0x12, 0x99, 0x2f, 0xc5, 0xb1, 0x5f, 0x86, 0x64, 0xff,
	0x7e, 0x92, 0x65, 0xc9, 0x04, 0xb7, 0x09, 0x73, 0x58, 0x7c, 0xdf, 0x56, 0x7c, 0x8a, 0x52, 0x85,
	0xd3, 0xbc, 0x4c, 0xf3, 0xbe, 0xc1, 0x7f, 0xfb, 0xb9, 0x44, 0xa1, 0x5e, 0x51, 0x46, 0x80, 0x47,
	0xec, 0x39, 0xb4, 0xcb, 0x74, 0xb7, 0x31, 0x68, 0x6c, 0x3a, 0x3b, 0x1b, 0xfe, 0x22, 0x6a, 0xdf,
	0x24, 0x18, 0x2c, 0xfb, 0x1f, 0xda, 0x5c, 0x8e, 0x53, 0x3c, 0x71, 0x9b, 0x83, 0xc6, 0x66, 0x37,
	0x68, 0x71, 0xf9, 0x16, 0x4f, 0xbc, 0x9f, 0xe7, 0xf8, 0x65, 0x7e, 0x4b, 0xfe, 0x3e, 0x74, 0x79,
	0xaa, 0x89, 0x30, 0xa6, 0x13, 0xac, 0xe0, 0xd4, 0x66, 0x2e, 0x74, 0x8a, 0x3c, 0x0e, 0x75, 0xc8,
	0xa2, 0x50, 0x65, 0x7a, 0x3e, 0xac, 0x8e, 0xd2, 0xb3, 0xe3, 0xa5, 0x3e, 0x7f, 0x9e, 0xa9, 0x51,
	0x67, 0xf2, 0xb6, 0x60, 0x75, 0x88, 0x13, 0x54, 0x38, 0x87, 0x77, 0xa1, 0x13, 0x93, 0xaf, 0x82,
	0x57, 0xa6, 0x77, 0x17, 0xac, 0xd1, 0x50, 0xb2, 0x55, 0xb0, 0x78, 0x2c, 0xdd, 0xc6, 0xc0, 0xda,
	0xb4, 0x03, 0xfd, 0xa9, 0x69, 0xf6, 0xa9, 0x82, 0x3a, 0x4d, 0x55, 0x64, 0xa3, 0x5e, 0xe4, 0x1b,
	0x58, 0x79, 0xcd, 0xd3, 0x78, 0x0e, 0xfb, 0x02, 0x3a, 0xa6, 0x0d, 0xc4, 0x7a, 0x5d, 0x8f, 0x2a,
	0xb0, 0xb7, 0x0b, 0x1d, 0xc3, 0x72, 0x6b, 0x8a, 0xdf, 0xcd, 0x7a, 0x35, 0x78, 0x74, 0xf1, 0x7e,
	0x6c, 0x0d, 0x5a, 0x47, 0x05, 0x8a, 0x19, 0x29, 0x61, 0x07, 0xa5, 0xc1, 0x9e, 0x42, 0x4b, 0xaa,
	0x50, 0x28, 0x12, 0xc1, 0xd9, 0xe9, 0xfb, 0xe5, 0xf0, 0xf9, 0xd5, 0xf0, 0xf9, 0x1f, 0xab, 0xe1,
	0x0b, 0x4a, 0x20, 0xdb, 0x02, 0x0b, 0xd3, 0xd8, 0x5d, 0xba, 0x16, 0xaf, 0x61, 0x6c, 0x03, 0x6c,
	0x9e, 0x46, 0x93, 0x42, 0xf2, 0x63, 0x74, 0x5b, 0x34, 0x65, 0x67, 0x0e, 0x76, 0x07, 0xda, 0x3f,
	0x78, 0x1c, 0x63, 0xea, 0xb6, 0x29, 0x64, 0x2c, 0xc6, 0x60, 0x49, 0x66, 0x42, 0xb9, 0x1d, 0x2a,
	0x9f, 0xbe, 0xd9, 0x3a, 0x74, 0x73, 0x14, 0xe3, 0x3c, 0x4c, 0xd0, 0xed, 0x96, 0x62, 0xe4, 0x28,
	0xde, 0x87, 0x09, 0xb2, 0x07, 0xb0, 0x1c, 0x15, 0x42, 0x60, 0xaa, 0xca, 0xb0, 0x4d, 0x61, 0xc7,
	0xf8, 0x34, 0xc4, 0xfb, 0x65, 0x41, 0xbb, 0x6c, 0x0f, 0x5b, 0x81, 0xe6, 0x68, 0x48, 0x7a, 0xda,
	0x41, 0x73, 0x34, 0xd4, 0x87, 0xa5, 0xe1, 0x14, 0x4d, 0x5f, 0xe8, 0x9b, 0x0a, 0x98, 0x14, 0x09,
	0x75, 0x45, 0x17, 0x30, 0x29, 0x12, 0xf6, 0x10, 0x7a, 0x31, 0x97, 0xf9, 0x24, 0x9c, 0x8d, 0x33,
	0x11, 0xa3, 0xa0, 0x16, 0x2c, 0x05, 0xcb, 0xc6, 0xf9, 0x4e, 0xfb, 0xd8, 0x00, 0x9c, 0x18, 0x65,
	0x24, 0x78, 0xae, 0x78, 0x96, 0xd2, 0x8d, 0xed, 0x60, 0xde, 0x75, 0xe9, 0x9d, 0x4f, 0x95, 0xe8,
	0xfc, 0xa3, 0x12, 0xdd, 0x9b, 0x29, 0xf1, 0x12, 0x20, 0x12, 0xa8, 0x87, 0x77, 0x1c, 0x2a, 0x6a,
	0xd1, 0xd5, 0x49, 0xb6, 0x41, 0xef, 0x2a, 0x9d, 0x6a, 0xe6, 0x5e, 0xa7, 0xc2, 0xf5, 0xa9, 0x06,
	0xbd, 0xab, 0x48, 0x9a, 0x50, 0x61, 0x92, 0x89, 0xd9, 0x58, 0x0f, 0xa4, 0x43, 0x8a, 0x3a, 0x95,
	0x6f, 0x14, 0xcb, 0x9d, 0x3f, 0x16, 0xf4, 0x4a, 0x69, 0x3e, 0xa0, 0x38, 0xe6, 0x11, 0xb2, 0xaf,
	0xb0, 0x3c, 0xbf, 0x80, 0xd8, 0xe3, 0xc5, 0xcf, 0xe0, 0xdc, 0x12, 0xec, 0xdf, 0x04, 0x26, 0x73,
	0x76, 0x00, 0xbd, 0xda, 0x7e, 0x61, 0xf7, 0xae, 0x7a, 0x65, 0xb2, 0xff, 0x64, 0x71, 0xf8, 0xc2,
	0x8e, 0x3a, 0x80, 0x5e, 0x6d, 0x81, 0xdc, 0x92, 0xf7, 0xc2, 0x12, 0xfa, 0x0c, 0xce, 0xdc, 0xe3,
	0x66, 0x8f, 0x16, 0xa7, 0xd5, 0xdf, 0x7f, 0xff, 0x06, 0x28, 0x99, 0xb3, 0x4f, 0xc0, 0x6a, 0xab,
	0x73, 0x6f, 0xa6, 0x77, 0xe3, 0xfa, 0x25, 0x17, 0x1e, 0x5e, 0x5a, 0xf3, 0xf9, 0xfd, 0xbb, 0xd7,
	0xfd, 0x62, 0xfe, 0x03, 0x0e, 0xdb, 0x34, 0x1f, 0xcf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x22,
	0x02, 0x9e, 0x38, 0x07, 0x07, 0x00, 0x00,
}
